name: Check for Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 5'

env:
  REPO: coolsnowwolf/lede
  REPO_BRANCH: master

jobs:
  job:
    name: Check for updates
    runs-on: ubuntu-18.04

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Download source code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.REPO_BRANCH }}
          path: openwrt
          fetch-depth: 1

      - name: Get latest commit hash
        run: |
          cd openwrt
          echo "LATEST_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "latest_hash: $LATEST_HASH"

      - name: Read cache hash
        id: read-cache
        uses: actions/cache@v2
        with:
          path: hash.cache
          key: commit-${{ env.LATEST_HASH }}

      - name: Update cache
        if: success() && steps.read-cache.outputs.cache-hit != 'true'
        run: |
          echo $LATEST_HASH > hash.cache

      - name: Trigger build
        if: success() && steps.read-cache.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: updated

      - name: Bark notify
        if: success() && steps.read-cache.outputs.cache-hit != 'true'
        uses: shink/bark-action@v1
        with:
          key: ${{ secrets.BARK_KEY }}
          title: New commit record found in ${{ env.REPO }}
          body: compilation job has started
          url: https://github.com/${{ github.repository }}/actions?query=is%3Ain_progress

      # Delete workflow runs
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 3
